In [2]:
import numpy as np
import sympy as sym

x_1, x_2, x_3, x_4 = sym.symbols('x_1, x_2, x_3, x_4')
y_1, y_2, y_3, y_4 = sym.symbols('y_1, y_2, y_3, y_4')
XY = sym.Matrix([sym.symbols('x_1, x_2, x_3, x_4'), sym.symbols('y_1, y_2, y_3, y_4')]).transpose()
xi, eta = sym.symbols('xi, eta')
basis = sym.Matrix([xi, eta])
N1 = (1-xi)*(1-eta)/4
N2 = (1+xi)*(1-eta)/4
N3 = (1+xi)*(1+eta)/4
N4 = (1-xi)*(1+eta)/4
NN = sym.Matrix([N1, N2, N3, N4])

coordinate = (NN.transpose()*XY).transpose()

NN_diff = NN.jacobian(basis)
jacob = coordinate.jacobian(basis)

jacob_det = sym.det(jacob)
jacob_inv = sym.inv_quick(jacob)

NN_diff_global = (NN_diff*jacob_inv)
temp = NN_diff_global*NN_diff_global.transpose()/jacob_det

sq3 = np.sqrt(1/3)

In [3]:
NN

Matrix([
[(1 - eta)*(1 - xi)/4],
[(1 - eta)*(xi + 1)/4],
[(eta + 1)*(xi + 1)/4],
[(1 - xi)*(eta + 1)/4]])

In [34]:
coordinate

Matrix([
[x_1*(1 - eta)*(1 - xi)/4 + x_2*(1 - eta)*(xi + 1)/4 + x_3*(eta + 1)*(xi + 1)/4 + x_4*(1 - xi)*(eta + 1)/4],
[y_1*(1 - eta)*(1 - xi)/4 + y_2*(1 - eta)*(xi + 1)/4 + y_3*(eta + 1)*(xi + 1)/4 + y_4*(1 - xi)*(eta + 1)/4]])

In [35]:
jacob

Matrix([
[-x_1*(1 - eta)/4 + x_2*(1 - eta)/4 + x_3*(eta + 1)/4 - x_4*(eta + 1)/4, -x_1*(1 - xi)/4 - x_2*(xi + 1)/4 + x_3*(xi + 1)/4 + x_4*(1 - xi)/4],
[-y_1*(1 - eta)/4 + y_2*(1 - eta)/4 + y_3*(eta + 1)/4 - y_4*(eta + 1)/4, -y_1*(1 - xi)/4 - y_2*(xi + 1)/4 + y_3*(xi + 1)/4 + y_4*(1 - xi)/4]])

In [36]:
jacob.subs(([x_1, -0.7], [x_2, 0.2], [x_3, 0.8], [x_4, 0], [y_1, 0.3], [y_2, -0.8], [y_3, 0], [y_4, 0.8]))

Matrix([
[0.425 - 0.025*eta, 0.325 - 0.025*xi],
[0.075*eta - 0.475, 0.075*xi + 0.325]])

In [37]:
jacob.subs(([xi, sq3], [eta, -sq3], [x_1, -0.8], [x_2, 0], [x_3, 0.8], [x_4, 0], [y_1, 0], [y_2, -0.8], [y_3, 0], [y_4, 0.8]))

Matrix([
[ 0.5, 0.5],
[-0.5, 0.5]])

In [38]:
jaco_inv = sym.inv_quick(jaco)
jaco_inv

Matrix([
[1.25, -1.25],
[1.25,  1.25]])

In [39]:
NN_diff.subs(([xi, sq3], [eta, -sq3]))

Matrix([
[-0.394337567297406, -0.105662432702594],
[ 0.394337567297406, -0.394337567297406],
[ 0.105662432702594,  0.394337567297406],
[-0.105662432702594,  0.105662432702594]])

In [40]:
NN_diff

Matrix([
[ eta/4 - 1/4,  xi/4 - 1/4],
[ 1/4 - eta/4, -xi/4 - 1/4],
[ eta/4 + 1/4,  xi/4 + 1/4],
[-eta/4 - 1/4,  1/4 - xi/4]])

In [41]:
jacob_det

-eta*x_1*y_2/8 + eta*x_1*y_3/8 + eta*x_2*y_1/8 - eta*x_2*y_4/8 - eta*x_3*y_1/8 + eta*x_3*y_4/8 + eta*x_4*y_2/8 - eta*x_4*y_3/8 - x_1*xi*y_3/8 + x_1*xi*y_4/8 + x_1*y_2/8 - x_1*y_4/8 + x_2*xi*y_3/8 - x_2*xi*y_4/8 - x_2*y_1/8 + x_2*y_3/8 + x_3*xi*y_1/8 - x_3*xi*y_2/8 - x_3*y_2/8 + x_3*y_4/8 - x_4*xi*y_1/8 + x_4*xi*y_2/8 + x_4*y_1/8 - x_4*y_3/8

In [42]:
jacob_inv

Matrix([
[   (-y_1*(1 - xi)/4 - y_2*(xi + 1)/4 + y_3*(xi + 1)/4 + y_4*(1 - xi)/4)/((-x_1*(1 - eta)/4 + x_2*(1 - eta)/4 + x_3*(eta + 1)/4 - x_4*(eta + 1)/4)*(-y_1*(1 - xi)/4 - y_2*(xi + 1)/4 + y_3*(xi + 1)/4 + y_4*(1 - xi)/4) - (-x_1*(1 - xi)/4 - x_2*(xi + 1)/4 + x_3*(xi + 1)/4 + x_4*(1 - xi)/4)*(-y_1*(1 - eta)/4 + y_2*(1 - eta)/4 + y_3*(eta + 1)/4 - y_4*(eta + 1)/4)),      (x_1*(1 - xi)/4 + x_2*(xi + 1)/4 - x_3*(xi + 1)/4 - x_4*(1 - xi)/4)/((-x_1*(1 - eta)/4 + x_2*(1 - eta)/4 + x_3*(eta + 1)/4 - x_4*(eta + 1)/4)*(-y_1*(1 - xi)/4 - y_2*(xi + 1)/4 + y_3*(xi + 1)/4 + y_4*(1 - xi)/4) - (-x_1*(1 - xi)/4 - x_2*(xi + 1)/4 + x_3*(xi + 1)/4 + x_4*(1 - xi)/4)*(-y_1*(1 - eta)/4 + y_2*(1 - eta)/4 + y_3*(eta + 1)/4 - y_4*(eta + 1)/4))],
[(y_1*(1 - eta)/4 - y_2*(1 - eta)/4 - y_3*(eta + 1)/4 + y_4*(eta + 1)/4)/((-x_1*(1 - eta)/4 + x_2*(1 - eta)/4 + x_3*(eta + 1)/4 - x_4*(eta + 1)/4)*(-y_1*(1 - xi)/4 - y_2*(xi + 1)/4 + y_3*(xi + 1)/4 + y_4*(1 - xi)/4) - (-x_1*(1 - xi)/4 - x_2*(xi + 1)/4 + x_3*(xi + 1)

In [46]:
D

Matrix([
[1, 1],
[1, 1]])

In [53]:
a = NN_diff_global.subs(([xi, -sq3], [eta, -sq3], [x_1, -0.8], [x_2, 0], [x_3, 0.8], [x_4, 0], [y_1, 0], [y_2, -0.8], [y_3, 0], [y_4, 0.8]))

In [54]:
b = NN_diff_global.subs(([xi, sq3], [eta, -sq3], [x_1, -0.8], [x_2, 0], [x_3, 0.8], [x_4, 0], [y_1, 0], [y_2, -0.8], [y_3, 0], [y_4, 0.8]))

In [55]:
c = NN_diff_global.subs(([xi, sq3], [eta, +sq3], [x_1, -0.8], [x_2, 0], [x_3, 0.8], [x_4, 0], [y_1, 0], [y_2, -0.8], [y_3, 0], [y_4, 0.8]))

In [56]:
d = NN_diff_global.subs(([xi, -sq3], [eta, +sq3], [x_1, -0.8], [x_2, 0], [x_3, 0.8], [x_4, 0], [y_1, 0], [y_2, -0.8], [y_3, 0], [y_4, 0.8]))

In [57]:
a

Matrix([
[-0.985843918243516,      0],
[ 0.360843918243516, -0.625],
[ 0.264156081756484,      0],
[ 0.360843918243516,  0.625]])

In [67]:
aa = np.array(a, dtype=np.float32)
bb = np.array(b, dtype=np.float32)
cc = np.array(c, dtype=np.float32)
dd = np.array(d, dtype=np.float32)

In [68]:
aa

array([[-0.9858439 ,  0.        ],
       [ 0.36084393, -0.625     ],
       [ 0.26415607,  0.        ],
       [ 0.36084393,  0.625     ]], dtype=float32)

In [66]:
np.einsum('mi,ni->imn', aa, aa)*0.32

array([[[ 0.31100422, -0.11383545, -0.08333333, -0.11383545],
        [-0.11383545,  0.04166667,  0.03050212,  0.04166667],
        [-0.08333333,  0.03050212,  0.0223291 ,  0.03050212],
        [-0.11383545,  0.04166667,  0.03050212,  0.04166667]],

       [[ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.125     ,  0.        , -0.125     ],
        [ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        , -0.125     ,  0.        ,  0.125     ]]],
      dtype=float32)

In [69]:
(np.einsum('mi,ni->imn', aa, aa)+np.einsum('mi,ni->imn', bb, bb)+\
np.einsum('mi,ni->imn', cc, cc)+np.einsum('mi,ni->imn', dd, dd))*0.32

array([[[ 0.5833333 , -0.08333333, -0.41666663, -0.08333333],
        [-0.08333333,  0.08333334, -0.08333333,  0.08333334],
        [-0.41666663, -0.08333333,  0.5833333 , -0.08333333],
        [-0.08333333,  0.08333334, -0.08333333,  0.08333334]],

       [[ 0.08333334, -0.08333333,  0.08333334, -0.08333333],
        [-0.08333333,  0.5833333 , -0.08333333, -0.41666663],
        [ 0.08333334, -0.08333333,  0.08333334, -0.08333333],
        [-0.08333333, -0.41666663, -0.08333333,  0.5833333 ]]],
      dtype=float32)